// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acttrzylqgiydiypstww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdHRyenlscWdpeWRpeXBzdHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzI0MDAsImV4cCI6MjA3MzQ0ODQwMH0.Te7ZUE1yRiaLubSPiD7CFDs5YA4r9RIiK1GD_rp88TU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});